[package]
name = "generate-drawing-examples"
version = "0.1.0"
authors = ["Ralf Fuest <mail@rfuest.de>"]
edition = "2018"
publish = false

[dependencies]
embedded-graphics = { path = "../../" }
png-target = { path = "../png-target/" }
tinytga = "0.4.0-beta.1"
regex = "1.4.3"
unindent = "0.1.7"
