[package]
name = "convert-fonts"
version = "0.1.0"
authors = ["Ralf Fuest <mail@rfuest.de>"]
edition = "2021"
publish = false

[dependencies]
bdf-to-mono = { path = "../bdf-to-mono" }
anyhow = "1.0.38"
bdf-parser = { version = "0.1.0" }
base64 = "0.13.0"
