[workspace]
members = [
    "bdf-to-mono",
    "convert-fonts",
    "generate-drawing-examples",
    "png-target",
    "check-md-refs"
]

[patch.crates-io]
embedded-graphics = { path = "../" }
embedded-graphics-core = { path = "../core" }
